export const navItems = [
  { id: "home", label: "Home" },
  { id: "about", label: "About Us" },
  { id: "portfolio", label: "Portfolio" },
  { id: "contact", label: "Contact" },
  // Tambahkan item navigasi lainnya sesuai kebutuhan
];


// Data Dummy for blogs (FIXED: SEO Friendly English ALTs)
export const blogs = [
  {
    id: 1,
    title: "Blog Post 1",
    description: "Lorem Ipsum is simply dummy text...",
    image: "/assets/dummy-blog.jpg",
    alt: "Illustration of Zerone Global educational technology blog article 1",
    author: "Zerone Global",
    date: "January 25, 2022",
  },
  {
    id: 2,
    title: "Blog Post 2",
    description: "This is a description of blog 2",
    image: "/assets/dummy-blog.jpg",
    alt: "Digital school management tips by Zerone Global",
    author: "Zerone Global",
    date: "January 26, 2022",
  },
  {
    id: 3,
    title: "Blog Post 3",
    description: "This is a description of blog 3",
    image: "/assets/dummy-blog.jpg",
    alt: "Latest school information system innovations",
    author: "Zerone Global",
    date: "January 27, 2022",
  },
  {
    id: 4,
    title: "Blog Post 4",
    description: "This is a description of blog 4",
    image: "/assets/dummy-blog.jpg",
    alt: "Guide to using Edunav application for teachers",
    author: "Zerone Global",
    date: "January 28, 2022",
  },
  {
    id: 5,
    title: "Blog Post 5",
    description: "This is a description of blog 5",
    image: "/assets/dummy-blog.jpg",
    alt: "Education transformation in the digital 4.0 era",
    author: "Zerone Global",
    date: "January 29, 2022",
  },
  {
    id: 6,
    title: "Blog Post 6",
    description: "This is a description of blog 6",
    image: "/assets/dummy-blog.jpg",
    alt: "Zerone Digital Global Solution service advantages",
    author: "Zerone Global",
    date: "January 30, 2022",
  },
  {
    id: 7,
    title: "Blog Post 7",
    description: "This is a description of blog 7",
    image: "/assets/dummy-blog.jpg",
    alt: "Latest feature updates for Latihan.id platform",
    author: "Zerone Global",
    date: "January 25, 2022",
  },
  {
    id: 8,
    title: "Blog Post 8",
    description: "This is a description of blog 8",
    image: "/assets/dummy-blog.jpg",
    alt: "Digital marketing strategies for educational institutions",
    author: "Zerone Global",
    date: "January 26, 2022",
  },
  {
    id: 9,
    title: "Blog Post 9",
    description: "This is a description of blog 9",
    image: "/assets/dummy-blog.jpg",
    alt: "Latest news on Indonesian educational technology",
    author: "Zerone Global",
    date: "January 27, 2022",
  },
  {
    id: 10,
    title: "Blog Post 10",
    description: "This is a description of blog 10",
    image: "/assets/dummy-blog.jpg",
    alt: "Zerone Global workshop activities with school partners",
    author: "Zerone Global",
    date: "January 28, 2022",
  },
];

// card portfolio (FIXED: SEO Friendly English ALTs)
const cards = [
  {
    id: 1,
    title: "Komodo Competition",
    alt: "Komodo Competition Math Event logo",
    description: "An online international math competition to hone your logic and problem-solving skills from home, take weekly quizzes, webinars, and compete globally.",
    image: "/assets/portfolio/komodo.webp",
    author: "Zerone Global",
    date: "January 25, 2022",
    link: "https://komodocompetition.com/",
  },
  {
    id: 2,
    title: "EDUSTEAM",
    alt: "EduSTEAM Indonesia STEAM learning platform", 
    description: "EduSTEAM – an online STEAM learning platform in Indonesia. Take interactive courses from certified teachers to hone your science, technology, engineering, art, and math skills.",
    image: "/assets/portfolio/steam.webp",
    author: "Zerone Global",
    date: "January 26, 2022",
    link: "https://edusteam.id/",
  },
  {
    id: 3,
    title: "Rajin.id",
    alt: "Rajin.id online UTBK tryout platform application", 
    description: "An online learning and tryout platform for preparing for the UTBK (Competency Test for the National Exam), university entrance exams, and institutional exams. Access classes and tryouts practically and effectively.",
    image: "/assets/portfolio/rajinID.webp",
    author: "Zerone Global",
    date: "January 27, 2022",
    link: "https://rajin.id/",
  },
  {
    id: 4,
    title: "ISPO",
    alt: "ISPO national science research competition",
    description: "A national science research competition for junior high, high school, and vocational high school students. Develop your creativity, innovation, and scientific abilities through projects in biology, physics, chemistry, technology, the environment, and computers.",
    image: "/assets/portfolio/ispo.webp",
    author: "Zerone Global",
    date: "January 30, 2022",
    link: "https://www.ispo.or.id/",
  },
  {
    id: 5,
    title: "BESS PROJECT",
    alt: "Bess Project school interior and laboratory design solution", 
    description: "Bess Project – a solution partner for educational institutions: design and construction of school spaces, laboratories, dormitories, and smart digital signage. Create a quality learning environment with our services.",
    image: "/assets/portfolio/bessproject.webp",
    author: "Zerone Global",
    date: "January 30, 2022",
    link: "https://www.bessproject.com/",
  },
  {
    id: 6,
    title: "HELLOGLOB",
    alt: "Helloglob US company incorporation services", 
    description: "Helloglob is a platform that helps individuals and businesses set up companies in the United States in an easy, safe, and structured manner. Services include establishing an LLC or Corporation, managing an EIN, trademark or patent, DUNS Number, and business address in the US without having to be present in person, with a process that complies with regulations.",
    image: "/assets/portfolio/helloglob.webp",
    author: "Zerone Global",
    date: "January 30, 2022",
    link: "https://helloglob.com",
  },
  {
    id: 7,
    title: "Festival Sains Budaya",
    alt: "National Science and Culture Festival event poster",
    description: "Science & Culture Festival – a national event for students to hone their creativity through science, arts, and culture. Join competitions, webinars, and virtual exhibitions. Register now!",
    image: "/assets/portfolio/festivalsainsbudaya.webp",
    author: "Zerone Global",
    date: "January 30, 2022",
    link: "https://festivalsainsbudaya.com/",
  },
  {
    id: 8,
    title: "EDUNAV",
    alt: "Edunav cloud-based School Information System dashboard", 
    description: "A cloud-based school information system for students, teachers, and parents. Monitor academics, attendance, finances, and school communications in one platform.",
    image: "/assets/portfolio/edunav.webp",
    author: "Zerone Global",
    date: "January 30, 2022",
    link: "https://www.edunav.net/",
  },
  {
    id: 9,
    title: "VENTI",
    alt: "Venti event management application for seminars and competitions", 
    description: "An online event management and discovery platform. Easily find or create events, from seminars and workshops to competitions and virtual runs.",
    image: "/assets/portfolio/venti.webp",
    author: "Zerone Global",
    date: "January 30, 2022",
    link: "https://venti.id/",
  },
  {
    id: 10,
    title: "EDUCAMP",
    alt: "Educamp professional teacher training program",
    description: "EduCamp – the Academy of Future Teachers program for aspiring teachers in Indonesia. Receive teaching training, classroom observations, professional mentorship, and job opportunities in schools.",
    image: "/assets/portfolio/educamp.webp",
    author: "Zerone Global",
    date: "January 30, 2022",
    link: "https://v2.educamp.co.id/",
  },
  {
    id: 11,
    title: "LATIHAN.ID",
    alt: "Latihan.id secure online exam platform",
    description: "An online exam and practice platform with proctoring, automated evaluation, and comprehensive reporting. Ready to help you prepare for your exams anytime.",
    image: "/assets/portfolio/latihan.webp",
    author: "Zerone Global",
    date: "January 30, 2022",
    link: "https://latihan.id/login",
  },
  {
    id: 12,
    title: "EDUFLIP",
    alt: "Eduflip application for flipped classroom learning method", 
    description: "Eduflip is a digital learning platform to support the flipped classroom through structured videos, interactive materials, and real-time monitoring of student progress.",
    image: "/assets/portfolio/eduflip.webp",
    author: "Zerone Global",
    date: "January 30, 2022",
    link: "https://Eduflip.id",
  },
];
export default cards;

export const stackDev = {
  aws: "/assets/stack/aws.png",
  mysql: "/assets/stack/mysql.png",
  php: "/assets/stack/php.png",
  wix: "/assets/stack/wix.png",
  java: "/assets/stack/java.png",
  android: "/assets/stack/android.png",
  google: "/assets/stack/google.png",
  laravel: "/assets/stack/laravel.png",
  wordpress: "/assets/stack/wordpress.png",
  microsoftnet: "/assets/stack/microsoft.png",
  nextjs: "/assets/stack/nextjs.png",
  vercel: "/assets/stack/vercel.png",
  react: "/assets/stack/react.png",
  node: "/assets/stack/node.png",
  flutter: "/assets/stack/flutter.png",
};

export const logos = {
  whitelogo: "/assets/Zerone-Putih.png",
  bluelogo: "/assets/Zerone-biru.png",
  komdigi: "/assets/komdigi.png",
  playstore: "/assets/playstore.png",
  appStore: "/assets/AppStore.png",
  instagram: "/assets/Instagram.webp",
  whatsappWhite : "/assets/whatsapp.png",
  instagramWhite : "/assets/instagram.png",
  emailWhite : "/assets/email.png",
  img404 : "/assets/404.webp"
};

export const mockup = {
  webapp: "/assets/mockup/webApp.webp",
  mobileapp: "/assets/mockup/mobileApp.webp",
  wordpress: "/assets/mockup/WORDPRESS.webp",
  cms: "/assets/mockup/cms.webp",
  uiux: "/assets/mockup/uiux.webp",
  digmar: "/assets/mockup/digmar.webp",
  payment: "/assets/mockup/payment.webp",
  digcon: "/assets/mockup/digitalconsulting.webp",
  graphic: "/assets/mockup/desaingrafis.webp",
  zeroneAI: "/assets/mockup/zeroneAI.webp",
};

// Solution Data Image
export const solutionAI = {
  ai1: "/assets/mockup/AI/1.webp",
  ai2: "/assets/mockup/AI/2.webp",
  ai3: "/assets/mockup/AI/3.webp",
  ai4: "/assets/mockup/AI/4.webp",
  ai5: "/assets/mockup/AI/5.webp",
  ai6: "/assets/mockup/AI/6.webp",
};
export const solutionUIUX = {
  uiux1: "/assets/mockup/UIUX/EdunavParentThumbnail.webp",
  uiux2: "/assets/mockup/UIUX/Edunav Student Thumbnail.webp",
  uiux3: "/assets/mockup/UIUX/Edunav Teacher Thumbnail.webp",
  uiux4: "/assets/mockup/UIUX/Edunav Web-app Thumbnail.webp",
  uiux5: "/assets/mockup/UIUX/Helloglob Thumbnail.webp",
  uiux6: "/assets/mockup/UIUX/Latihan.id Mockup 1.webp",
  uiux7: "/assets/mockup/UIUX/Latihan.id Mockup 2.webp",
  uiux8: "/assets/mockup/UIUX/Writing Aide.webp",
};
export const solutionDesain = {
  desain1: "/assets/mockup/desain/zerone.webp",
  desain2: "/assets/mockup/desain/edunav.webp",
  desain3: "/assets/mockup/desain/venti.webp",
};
export const solutionWordpress = {
  webpres1: "/assets/mockup/web-design/pakar-belia.webp",
  webpres2: "/assets/mockup/web-design/hibiscus.webp",
  webpres3: "/assets/mockup/web-design/kesatuan-bangsa.webp",
  webpres4: "/assets/mockup/web-design/competition-website.webp",
  webpres5: "/assets/mockup/web-design/edunav.webp",
  webpres6: "/assets/mockup/web-design/semesta.webp",
};
export const solutionAppDev = {
  appDev1: "/assets/mockup/AppDev/latihan.webp",
  appDev2: "/assets/mockup/AppDev/venti.webp",
  appDev3: "/assets/mockup/AppDev/rajin.webp",
};
export const solutionWebApp = {
  webApp1: "/assets/mockup/webApp/dashboard edunav.webp",
  webApp2: "/assets/mockup/webApp/dashboard latihanID.webp",
  webApp3: "/assets/mockup/webApp/dashboard venti.webp",
};
export const solutionpayment = {
  payment1: "/assets/mockup/payment/payment gateway.webp",
  payment2: "/assets/mockup/payment/pay - payment gateway.webp",
  payment3: "/assets/mockup/payment/confirmation - payment gateway.webp",
};
export const solutionDigmar = {
  digmar1: "/assets/mockup/digmar/1.webp",
  digmar2: "/assets/mockup/digmar/2.webp",
  digmar3: "/assets/mockup/digmar/3.webp",
};
export const solutionDigitalStrategy = {
  digstra1: "/assets/mockup/digitalStrategi/digital strategy consulting.webp",
};
// End Solution Data Image

export const heroImage = {
  image: "/assets/device-hero.webp",
  bgHero: "/assets/bg-hero.webp",
  visi: "/assets/Vision.png",
  misi: "/assets/Mission.png",
  bgHorizontal: "/assets/bg-linear.webp",
  visimisi: "/assets/bg-vm.png",
};
export const whychoose = {
  whychooseus: "/assets/lp/whychooseus.webp",
};

export const banner = {
  edunav: "/assets/banner-produk/edunav.webp",
  venti: "/assets/banner-produk/venti.webp",
  jadwalkuliah: "/assets/banner-produk/jadwalkuliah.webp",
  latihan: "/assets/banner-produk/latihan.webp",
  rajin: "/assets/banner-produk/rajin.webp",
  writingaide: "/assets/banner-produk/writingaide.webp",
  maridukung: "/assets/banner-produk/maridukung.webp",
  mobileedunav: "/assets/banner-produk/Mobile/edunav.webp",
  mobileventi: "/assets/banner-produk/Mobile/venti.webp",
  mobilejadwalkuliah: "/assets/banner-produk/Mobile/jadwal.webp",
  mobilelatihan: "/assets/banner-produk/Mobile/latihan.webp",
  mobilerajin: "/assets/banner-produk/Mobile/rajin.webp",
  mobilewritingaide: "/assets/banner-produk/Mobile/writing.webp",
  mobilemaridukung: "/assets/banner-produk/Mobile/maridukung.webp",
};
export const sosialmedia = {
  socialEdunav: "/assets/banner-produk/sosmed/sosmed-edunav.webp",
  socialVenti: "/assets/banner-produk/sosmed/sosmed-venti.webp",
  socialRajin: "/assets/banner-produk/sosmed/sosmed-rajin.webp",
  socialMaridukung: "/assets/banner-produk/sosmed/sosmed-maridukung.webp",
  socialWritingAide: "/assets/banner-produk/sosmed/sosmed-writing-aide.webp",
};

export const ourteam = {
  team1: "/assets/OurTeam/team1.png",
  team2: "/assets/OurTeam/2.png",
  team3: "/assets/OurTeam/3.png",
  team4: "/assets/OurTeam/4.png",
  team5: "/assets/OurTeam/5.png",
  team6: "/assets/OurTeam/6.png",
  team7: "/assets/OurTeam/7.png",
  team8: "/assets/OurTeam/8.png",
  team9: "/assets/OurTeam/9.png",
  team10: "/assets/OurTeam/10.png",
  team11: "/assets/OurTeam/11.png",
};

export const ilustration = {
  ilusAbout1: "/assets/iconilustration/collaborative.png",
  ilusAbout2: "/assets/iconilustration/customer.png",
  ilusAbout3: "/assets/iconilustration/support.png",
  ilusEdunav2: "/assets/iconilustration/sp-edunav/1.png",
  ilusEdunav3: "/assets/iconilustration/sp-edunav/2.png",
  ilusEdunav1: "/assets/iconilustration/sp-edunav/3.png",
  ilusventi1: "/assets/iconilustration/sp-venti/1.png",
  ilusventi2: "/assets/iconilustration/sp-venti/2.png",
  ilusventi3: "/assets/iconilustration/sp-venti/3.png",
  iluslatihan1: "/assets/iconilustration/sp-latihan/1.png",
  iluslatihan2: "/assets/iconilustration/sp-latihan/2.png",
  iluslatihan3: "/assets/iconilustration/sp-latihan/3.png",
  iluslatihan4: "/assets/iconilustration/sp-latihan/4.png",
  iluslatihan5: "/assets/iconilustration/sp-latihan/5.png",
  ilusrajin1: "/assets/iconilustration/sp-rajin/1.png",
  ilusrajin2: "/assets/iconilustration/sp-rajin/2.png",
  ilusrajin3: "/assets/iconilustration/sp-rajin/3.png",
  iluswriting1: "/assets/iconilustration/sp-writingaide/1.png",
  iluswriting2: "/assets/iconilustration/sp-writingaide/2.png",
  iluswriting3: "/assets/iconilustration/sp-writingaide/3.png",
  iluswriting4: "/assets/iconilustration/sp-writingaide/4.png",
  ilusmaridukung1: "/assets/iconilustration/sp-maridukung/1.png",
  ilusmaridukung2: "/assets/iconilustration/sp-maridukung/2.png",
  ilusmaridukung3: "/assets/iconilustration/sp-maridukung/3.png",
  ilusjadwalkuliah1: "/assets/iconilustration/sp-jadwalkuliah/1.png",
  ilusjadwalkuliah2: "/assets/iconilustration/sp-jadwalkuliah/2.png",
  ilusjadwalkuliah3: "/assets/iconilustration/sp-jadwalkuliah/3.png",
};

export const servicesFeatures = {
  cms: "/assets/services/cms.png",
  appDev: "/assets/services/mobile-app.png",
  webDev: "/assets/services/webDev.png",
  wordpress: "/assets/services/wordpress.png",
  uiux: "/assets/services/uiux.png",
  digmar: "/assets/services/digmar.png",
  payment: "/assets/services/payment-gateway.png",
  desain: "/assets/services/desain-grafis.png",
  strategy: "/assets/services/strategy-consulting.png",
};

export const partnerLogos = [
  {
    id: 1,
    name: "Al-Azhar BSD",
    image: "/assets/logo-partner/alazhar-bsd.png",
    alt: "logo partner yang menggunakan Edunav sebagai Sistem Informasi Sekolah by. Zerone Digital Global Solution",
  },
  {
    id: 2,
    name: "Al-Azhar Cileungsi",
    image: "/assets/logo-partner/alhazhar-cileungsi.png",
    alt: "logo partner yang menggunakan Edunav sebagai Sistem Informasi Sekolah by. Zerone Digital Global Solution",
  },
  {
    id: 3,
    name: "Cahaya Rancamaya",
    image: "/assets/logo-partner/cahaya-rancamaya.png",
    alt: "logo partner yang menggunakan Edunav sebagai Sistem Informasi Sekolah by. Zerone Digital Global Solution",
  },
  {
    id: 4,
    name: "Darul Hikmah",
    image: "/assets/logo-partner/darul-hikmah.png",
    alt: "logo partner yang menggunakan Edunav sebagai Sistem Informasi Sekolah by. Zerone Digital Global Solution",
  },
  {
    id: 5,
    name: "EIBOS",
    image: "/assets/logo-partner/eibos.png",
    alt: "logo partner yang menggunakan Edunav sebagai Sistem Informasi Sekolah by. Zerone Digital Global Solution",
  },
  {
    id: 6,
    name: "Fatih Bilingual School",
    image: "/assets/logo-partner/fatih.png",
    alt: "logo partner yang menggunakan Edunav sebagai Sistem Informasi Sekolah by. Zerone Digital Global Solution",
  },
  {
    id: 7,
    name: "Fountain",
    image: "/assets/logo-partner/fountain.png",
    alt: "logo partner yang menggunakan Edunav sebagai Sistem Informasi Sekolah by. Zerone Digital Global Solution",
  },
  {
    id: 8,
    name: "Global Cahaya Bangsa",
    image: "/assets/logo-partner/global-cahaya-bangsa.webp",
    alt: "logo partner yang menggunakan Edunav sebagai Sistem Informasi Sekolah by. Zerone Digital Global Solution",
  },
  {
    id: 9,
    name: "Harapan Ibu",
    image: "/assets/logo-partner/harapan-ibu.png",
    alt: "logo partner yang menggunakan Edunav sebagai Sistem Informasi Sekolah by. Zerone Digital Global Solution",
  },
  {
    id: 10,
    name: "Harmoni Wisdom",
    image: "/assets/logo-partner/harmoni-wisdom.png",
    alt: "logo partner yang menggunakan Edunav sebagai Sistem Informasi Sekolah by. Zerone Digital Global Solution",
  },
  {
    id: 11,
    name: "Hibiscus",
    image: "/assets/logo-partner/hibicus.png",
    alt: "logo partner yang menggunakan Edunav sebagai Sistem Informasi Sekolah by. Zerone Digital Global Solution",
  },
  {
    id: 12,
    name: "Horizon School",
    image: "/assets/logo-partner/horizon.png",
    alt: "logo partner yang menggunakan Edunav sebagai Sistem Informasi Sekolah by. Zerone Digital Global Solution",
  },
  {
    id: 13,
    name: "IIBS",
    image: "/assets/logo-partner/iibs.png",
    alt: "logo partner yang menggunakan Edunav sebagai Sistem Informasi Sekolah by. Zerone Digital Global Solution",
  },
  {
    id: 14,
    name: "IQ Belia",
    image: "/assets/logo-partner/iq-belia.png",
    alt: "logo partner yang menggunakan Edunav sebagai Sistem Informasi Sekolah by. Zerone Digital Global Solution",
  },
  {
    id: 15,
    name: "Kesatuan Bangsa",
    image: "/assets/logo-partner/kesatuan-bangsa.png",
    alt: "logo partner yang menggunakan Edunav sebagai Sistem Informasi Sekolah by. Zerone Digital Global Solution",
  },
  {
    id: 16,
    name: "Kharisma Bangsa",
    image: "/assets/logo-partner/kharisma.png",
    alt: "logo partner yang menggunakan Edunav sebagai Sistem Informasi Sekolah by. Zerone Digital Global Solution",
  },
  {
    id: 17,
    name: "MEGA",
    image: "/assets/logo-partner/mega.png",
    alt: "logo partner yang menggunakan Edunav sebagai Sistem Informasi Sekolah by. Zerone Digital Global Solution",
  },
  {
    id: 18,
    name: "MIP",
    image: "/assets/logo-partner/mip.png",
    alt: "logo partner yang menggunakan Edunav sebagai Sistem Informasi Sekolah by. Zerone Digital Global Solution",
  },
  {
    id: 19,
    name: "Prestige",
    image: "/assets/logo-partner/prestige.png",
    alt: "logo partner yang menggunakan Edunav sebagai Sistem Informasi Sekolah by. Zerone Digital Global Solution",
  },
  {
    id: 20,
    name: "Pribadi School",
    image: "/assets/logo-partner/pribadi.png",
    alt: "logo partner yang menggunakan Edunav sebagai Sistem Informasi Sekolah by. Zerone Digital Global Solution",
  },
  {
    id: 21,
    name: "Pribadi Bandung",
    image: "/assets/logo-partner/pribadi-bandung.png",
    alt: "logo partner yang menggunakan Edunav sebagai Sistem Informasi Sekolah by. Zerone Digital Global Solution",
  },
  {
    id: 22,
    name: "Pribadi Premier",
    image: "/assets/logo-partner/pribadi-premier.png",
    alt: "logo partner yang menggunakan Edunav sebagai Sistem Informasi Sekolah by. Zerone Digital Global Solution",
  },
  {
    id: 23,
    name: "Samarinda",
    image: "/assets/logo-partner/samarinda.png",
    alt: "logo partner yang menggunakan Edunav sebagai Sistem Informasi Sekolah by. Zerone Digital Global Solution",
  },
  {
    id: 24,
    name: "Sampoerna Academy",
    image: "/assets/logo-partner/sampoerna.png",
    alt: "logo partner yang menggunakan Edunav sebagai Sistem Informasi Sekolah by. Zerone Digital Global Solution",
  },
  {
    id: 25,
    name: "Saritha",
    image: "/assets/logo-partner/saritha.png",
    alt: "logo partner yang menggunakan Edunav sebagai Sistem Informasi Sekolah by. Zerone Digital Global Solution",
  },
  {
    id: 26,
    name: "Semesta",
    image: "/assets/logo-partner/semesta.png",
    alt: "logo partner yang menggunakan Edunav sebagai Sistem Informasi Sekolah by. Zerone Digital Global Solution",
  },
  {
    id: 27,
    name: "SMA Prestasi Samarinda",
    image: "/assets/logo-partner/sma prestasi samarinda.webp",
    alt: "logo partner yang menggunakan Edunav sebagai Sistem Informasi Sekolah by. Zerone Digital Global Solution",
  },
  {
    id: 28,
    name: "SMI CCI",
    image: "/assets/logo-partner/smi-cci.png",
    alt: "logo partner yang menggunakan Edunav sebagai Sistem Informasi Sekolah by. Zerone Digital Global Solution",
  },
  {
    id: 29,
    name: "SMP 16 Samarinda",
    image: "/assets/logo-partner/smp 16 samarinda.webp",
    alt: "logo partner yang menggunakan Edunav sebagai Sistem Informasi Sekolah by. Zerone Digital Global Solution",
  },
  {
    id: 30,
    name: "Teuku Nyak Arif",
    image: "/assets/logo-partner/teuku-nyak-arif.png",
    alt: "logo partner yang menggunakan Edunav sebagai Sistem Informasi Sekolah by. Zerone Digital Global Solution",
  },
  {
    id: 31,
    name: "TK SD Muslim Cendikia",
    image: "/assets/logo-partner/TK-SD-MUSLIM-CENDIKIA.png",
    alt: "logo partner yang menggunakan Edunav sebagai Sistem Informasi Sekolah by. Zerone Digital Global Solution",
  },
  {
    id: 32,
    name: "Tolerance",
    image: "/assets/logo-partner/tolerance.png",
    alt: "logo partner yang menggunakan Edunav sebagai Sistem Informasi Sekolah by. Zerone Digital Global Solution",
  },
];
